export const COLORS = {
  redSalsa: "#FB3748",
  mangoTango: "#FF8447",
  orangeYellow: "#F6B51E",
  shandy: "#FFE071",
  flavescent: "#FFE999",
  lemonChiffon: "#FFF4CC",
  green: "#1FC16B",
  maximumBlueGreen: "#22D3BB",
  vividSkyBlue: "#00D5FF",
  electricBlue: "#80EAFF",
  water: "#CCF7FF",
  ultramarineBlue: "#335CFF",
  royalBlue: "#4B73EC",
  frenchSkyBlue: "#809FFF",
  lavenderBlue: "#CCD9FF",
  mediumOrchid: "#C25CD6",
  brightLilac: "#E18CF2",
  shampoo: "#F5CFFC",
  lightSilver: "#D9D9D9",
} as const
