import {
  AddedIcon,
  AssignedIcon,
  CompletedIcon,
  MentionedIcon,
  RepliedIcon,
} from "./icons"
import type { IInboxEntry } from "./types"

import joeAvatar from "@/images/pages/home/inbox/joe-avatar.jpg"
import johnDoeAvatar from "@/images/pages/home/inbox/john-doe.jpg"
import oliverJamesAvatar from "@/images/pages/home/inbox/oliver-james.jpg"
import evanClarkAvatar from "@/images/pages/home/inbox/evan-clark.jpg"
import danielAvatar from "@/images/pages/home/inbox/daniel.png"
import rayAvatar from "@/images/pages/home/inbox/ray.png"
import aliceAvatar from "@/images/pages/home/inbox/alice.png"

import completeIcon from "@/svgs/pages/home/inbox/complete.svg"
import cubeIcon from "@/svgs/pages/home/inbox/cube.svg"
import rhombIcon from "@/svgs/pages/home/inbox/rhomb.svg"
import yellowHalfCircleIcon from "@/svgs/pages/home/inbox/yellow-half-circle.svg"

const inboxData: IInboxEntry[] = [
  {
    theme: "novuDark",
    title: "Novu dark",
    categories: ["All", "Projects", "Announcements"],
    messages: [
      {
        category: "Projects",
        title: "Your account is pending verification.",
        mail: "steve@acme.co",
        text: "is pending verification, please verify your account to protect against fraud and abuse.",
        date: "Today at 7:41 AM",
        isRead: false,
        buttons: ["Verify now"],
      },
      {
        category: "Projects",
        title: "Joe requested to view Q4 2024 report.",
        mail: "joe@acme.co",
        text: "requested view access to Q4 2024 report.",
        date: "Last Friday at 8:40 PM",
        isRead: false,
        avatar: joeAvatar.src,
        buttons: ["Verify now", "Deny"],
      },
      {
        category: "Projects",
        title: "2 new comments from Radek and Dima.",
        text: "You have 2 new comments on the Acme figma file.",
        date: "Last Monday at 13:45 PM",
        isRead: false,
      },
      {
        category: "Announcements",
        title: "Your account is pending verification.",
        mail: "steve@acme.co",
        text: "is pending verification, please verify your account to protect against fraud and abuse.",
        date: "Today at 7:41 AM",
        isRead: false,
        buttons: ["Verify now"],
      },
      {
        category: "Announcements",
        title: "Joe requested to view Q4 2024 report.",
        mail: "joe@acme.co",
        text: "requested view access to Q4 2024 report.",
        date: "Last Friday at 8:40 PM",
        isRead: false,
        avatar: joeAvatar.src,
        buttons: ["Verify now", "Deny"],
      },
      {
        category: "Announcements",
        title: "2 new comments from Radek and Dima.",
        text: "You have 2 new comments on the Acme figma file.",
        date: "Last Monday at 13:45 PM",
        isRead: false,
      },
    ],
  },
  {
    theme: "novuLight",
    title: "Novu Light",
    categories: ["All", "Projects", "Announcements"],
    messages: [
      {
        category: "Projects",
        title: "Your account is pending verification.",
        mail: "steve@acme.co",
        text: "is pending verification, please verify your account to protect against fraud and abuse.",
        date: "Today at 7:41 AM",
        isRead: false,
        buttons: ["Verify now"],
      },
      {
        category: "Announcements",
        title: "Joe requested to view Q4 2024 report.",
        mail: "joe@acme.co",
        text: "requested view access to Q4 2024 report.",
        date: "Last Friday at 8:40 PM",
        isRead: false,
        avatar: joeAvatar.src,
        buttons: ["Verify now", "Deny"],
      },
      {
        category: "Projects",
        title: "2 new comments from Radek and Dima.",
        text: "You have 2 new comments on the Acme figma file.",
        date: "Last Monday at 13:45 PM",
        isRead: false,
      },
      {
        category: "Projects",
        title: "Your account is pending verification.",
        mail: "steve@acme.co",
        text: "is pending verification, please verify your account to protect against fraud and abuse.",
        date: "Today at 7:41 AM",
        isRead: false,
        buttons: ["Verify now"],
      },
      {
        category: "Announcements",
        title: "Joe requested to view Q4 2024 report.",
        mail: "joe@acme.co",
        text: "requested view access to Q4 2024 report.",
        date: "Last Friday at 8:40 PM",
        isRead: false,
        avatar: joeAvatar.src,
        buttons: ["Verify now", "Deny"],
      },
      {
        category: "Projects",
        title: "2 new comments from Radek and Dima.",
        text: "You have 2 new comments on the Acme figma file.",
        date: "Last Monday at 13:45 PM",
        isRead: false,
      },
    ],
  },
  {
    theme: "notionDark",
    title: "Notion dark",
    messages: [
      {
        title: "Project Page",
        subtitle: "commented in",
        text: "Hey team! To improve clarity, I suggest adding priority labels, a recurring meeting schedule, and clearer task dependencies-thoughts",
        date: "1h",
        isRead: false,
        authors: [{ name: "John Doe", avatar: johnDoeAvatar.src }],
      },
      {
        title: "Weekly plan",
        subtitle: "mentioned you in",
        text: "For this week\u2019s plan, how about adding a quick progress tracker and a notes section for any blockers?",
        date: "2h",
        isRead: false,
        authors: [
          { name: "Oliver James", avatar: oliverJamesAvatar.src },
          { name: "Evan Clark", avatar: evanClarkAvatar.src },
        ],
      },
      {
        title: "Project Page",
        subtitle: "commented in",
        text: "Hey team! To improve clarity, I suggest adding priority labels, a recurring meeting schedule, and clearer task dependencies-thoughts",
        date: "1h",
        isRead: false,
        authors: [{ name: "John Doe", avatar: johnDoeAvatar.src }],
      },
    ],
  },
  {
    theme: "notionLight",
    title: "Notion light",
    messages: [
      {
        title: "Project Page",
        subtitle: "commented in",
        text: "Hey team! To improve clarity, I suggest adding priority labels, a recurring meeting schedule, and clearer task dependencies-thoughts",
        date: "1h",
        isRead: false,
        authors: [{ name: "John Doe", avatar: johnDoeAvatar.src }],
      },
      {
        title: "Weekly plan",
        subtitle: "mentioned you in",
        text: "For this week\u2019s plan, how about adding a quick progress tracker and a notes section for any blockers?",
        date: "2h",
        isRead: false,
        authors: [
          { name: "Oliver James", avatar: oliverJamesAvatar.src },
          { name: "Evan Clark", avatar: evanClarkAvatar.src },
        ],
      },
      {
        title: "Project Page",
        subtitle: "commented in",
        text: "Hey team! To improve clarity, I suggest adding priority labels, a recurring meeting schedule, and clearer task dependencies-thoughts",
        date: "1h",
        isRead: false,
        authors: [{ name: "John Doe", avatar: johnDoeAvatar.src }],
      },
    ],
  },
  {
    theme: "linearDark",
    title: "Linear Dark",
    messages: [
      {
        title: "Update youtube block preview",
        actionType: "mentioned you in project",
        avatarIcon: MentionedIcon,
        additionalText: "",
        date: "38min",
        dateIcon: cubeIcon.src,
        isRead: false,
        authors: [{ name: "Daniel", avatar: danielAvatar.src }],
      },
      {
        title: "Ensure compatibility with the mobile app and the web version.",
        actionType: "assigned to you",
        avatarIcon: AssignedIcon,
        additionalText: "",
        date: "2h",
        dateIcon: yellowHalfCircleIcon.src,
        isRead: false,
        authors: [{ name: "Ray", avatar: rayAvatar.src }],
      },
      {
        title: "Refactor user authentication flow",
        actionType: "marked as completed",
        avatarIcon: CompletedIcon,
        additionalText: "",
        date: "1h",
        dateIcon: completeIcon.src,
        isRead: true,
        authors: [{ name: "Daniel", avatar: danielAvatar.src }],
      },
      {
        title: "Create a new design for the hero section for improving user engagement.",
        actionType: "replied:",
        avatarIcon: RepliedIcon,
        additionalText: "Love it!",
        date: "3h",
        dateIcon: completeIcon.src,
        isRead: true,
        authors: [{ name: "Alice", avatar: aliceAvatar.src }],
      },
      {
        title: "Replace current cookie-based authentication with JWT tokens for enhanced security.",
        actionType: "added you to project",
        avatarIcon: AddedIcon,
        additionalText: "",
        date: "13h",
        dateIcon: cubeIcon.src,
        isRead: false,
        authors: [{ name: "Daniel", avatar: danielAvatar.src }],
      },
      {
        title: "User Testing Phase Start",
        actionType: "mentioned you in project",
        avatarIcon: MentionedIcon,
        additionalText: "milestone",
        date: "12h",
        dateIcon: rhombIcon.src,
        isRead: true,
        authors: [{ name: "Ray", avatar: rayAvatar.src }],
      },
    ],
  },
  {
    theme: "linearLight",
    title: "Linear Light",
    messages: [
      {
        title: "Update youtube block preview",
        actionType: "mentioned you in project",
        avatarIcon: MentionedIcon,
        additionalText: "",
        date: "38min",
        dateIcon: cubeIcon.src,
        isRead: false,
        authors: [{ name: "Daniel", avatar: danielAvatar.src }],
      },
      {
        title: "Ensure compatibility with the mobile app and the web version.",
        actionType: "assigned to you",
        avatarIcon: AssignedIcon,
        additionalText: "",
        date: "2h",
        dateIcon: yellowHalfCircleIcon.src,
        isRead: false,
        authors: [{ name: "Ray", avatar: rayAvatar.src }],
      },
      {
        title: "Refactor user authentication flow",
        actionType: "marked as completed",
        avatarIcon: CompletedIcon,
        additionalText: "",
        date: "1h",
        dateIcon: completeIcon.src,
        isRead: true,
        authors: [{ name: "Daniel", avatar: danielAvatar.src }],
      },
      {
        title: "Create a new design for the hero section for improving user engagement.",
        actionType: "replied:",
        avatarIcon: RepliedIcon,
        additionalText: "Love it!",
        date: "3h",
        dateIcon: completeIcon.src,
        isRead: true,
        authors: [{ name: "Alice", avatar: aliceAvatar.src }],
      },
      {
        title: "Replace current cookie-based authentication with JWT tokens for enhanced security.",
        actionType: "added you to project",
        avatarIcon: AddedIcon,
        additionalText: "",
        date: "13h",
        dateIcon: cubeIcon.src,
        isRead: false,
        authors: [{ name: "Daniel", avatar: danielAvatar.src }],
      },
      {
        title: "User Testing Phase Start",
        actionType: "mentioned you in project",
        avatarIcon: MentionedIcon,
        additionalText: "milestone",
        date: "12h",
        dateIcon: rhombIcon.src,
        isRead: true,
        authors: [{ name: "Ray", avatar: rayAvatar.src }],
      },
    ],
  },
]

export default inboxData
